apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-production
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/armaghanfazal/argocd-practice.git
    targetRevision: main
    path: environments/production

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  # No syncPolicy.automated = manual sync required
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
